# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<oss@fastly.com>"]
description = "A project for learning about edge computing."
language = "javascript"
manifest_version = 3
name = "Hello Compute"

[setup]
  [setup.backends]
    [setup.backends.app]
      description = "The static backend for the app"
      address = "127.0.0.1"
      port = 8000

[local_server]
  [local_server.static_dirs]
    [local_server.static_dirs.app]
      prefix = "/"
      directory = "dist"

[scripts]
  build = "npm run build"
  post_init = "npm install"
